### ISSUE TITLE
Nuxt put bad PrismaClient location in config files

### ISSUE THREAD

**Issue by l0seq** [prisma/nuxt-prisma#95]
Today, when I launched my nuxt server, it started to give me the following error:

`Cannot find module '/lib/generated/prisma' imported from /home/loseq/work/.nuxt/dev/index.mjs`

When I went to read the index.mjs file, I realized that it was trying to import the Prisma client in this way:

`import { PrismaClient } from '../../../../../../lib/generated/prisma';`

This redirects directly to the root of my system, as confirmed by the error cause:

```
Error {
  name: 'Error',
  message: "Cannot find module '/lib/generated/prisma' imported from 
  /home/loseq/work/.nuxt/dev/index.mjs",
  stack: "Cannot find module '/lib/generated/prisma' imported from  /home/loseq/work/.nuxt/dev/index.mjs\n" +
  '    at finalizeResolution (node:internal/modules/esm/resolve:283:11)\n' +
  '    at moduleResolve (node:internal/modules/esm/resolve:952:10)\n' +
  '    at defaultResolve (node:internal/modules/esm/resolve:1188:11)\n' +
  '    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)\n' +
  '    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)\n' +
  '    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)\n' +
  '    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)\n' +
  '    at link (node:internal/modules/esm/module_job:95:36)',
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///lib/generated/prisma',
  unhandled: false,
  [Symbol(Symbol.toStringTag)]: 'Error',
}

```

**Comment by AmanVarshney01** [comment]
Sadly, we are deprecating this module. You can read more about the explanation [here](https://github.com/prisma/nuxt-prisma/pull/112)

How to use Nuxt with Prisma 7 - https://www.prisma.io/docs/guides/nuxt
